name: CI-Good
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # GOOD: Фиксированная версия Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # Создаем фейковый package.json, чтобы npm install не падал (т.к. у нас пустой проект)
      - name: Create dummy project
        run: |
          npm init -y
          npm install express

      # GOOD: Установка с кэшем
      - name: Install
        run: npm ci

      # GOOD: Деплой с использованием секрета
      - name: Deploy
        env:
          MY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "Deploying..."
          # GitHub сам замажет секрет звездочками
          echo "Key used: $MY_KEY"
